// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: kafka_lite.proto

package kafka_lite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicaRole int32

const (
	ReplicaRole_LEADER   ReplicaRole = 0
	ReplicaRole_FOLLOWER ReplicaRole = 1
)

// Enum value maps for ReplicaRole.
var (
	ReplicaRole_name = map[int32]string{
		0: "LEADER",
		1: "FOLLOWER",
	}
	ReplicaRole_value = map[string]int32{
		"LEADER":   0,
		"FOLLOWER": 1,
	}
)

func (x ReplicaRole) Enum() *ReplicaRole {
	p := new(ReplicaRole)
	*p = x
	return p
}

func (x ReplicaRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicaRole) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_lite_proto_enumTypes[0].Descriptor()
}

func (ReplicaRole) Type() protoreflect.EnumType {
	return &file_kafka_lite_proto_enumTypes[0]
}

func (x ReplicaRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicaRole.Descriptor instead.
func (ReplicaRole) EnumDescriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_kafka_lite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Message) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Message) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type TopicPartition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPartition) Reset() {
	*x = TopicPartition{}
	mi := &file_kafka_lite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPartition) ProtoMessage() {}

func (x *TopicPartition) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPartition.ProtoReflect.Descriptor instead.
func (*TopicPartition) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{1}
}

func (x *TopicPartition) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicPartition) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Role          ReplicaRole            `protobuf:"varint,3,opt,name=role,proto3,enum=kafka_lite.ReplicaRole" json:"role,omitempty"`
	Epoch         int64                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	LeaderId      int32                  `protobuf:"varint,5,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,6,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	IsrIds        []int32                `protobuf:"varint,7,rep,packed,name=isr_ids,json=isrIds,proto3" json:"isr_ids,omitempty"` // initial ISR broker IDs (LEADER role only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_kafka_lite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{2}
}

func (x *AssignRoleRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AssignRoleRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *AssignRoleRequest) GetRole() ReplicaRole {
	if x != nil {
		return x.Role
	}
	return ReplicaRole_LEADER
}

func (x *AssignRoleRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AssignRoleRequest) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AssignRoleRequest) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

func (x *AssignRoleRequest) GetIsrIds() []int32 {
	if x != nil {
		return x.IsrIds
	}
	return nil
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_kafka_lite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{3}
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions    int32                  `protobuf:"varint,2,opt,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_kafka_lite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateTopicRequest) GetPartitions() int32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_kafka_lite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{5}
}

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_kafka_lite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{6}
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ProduceRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_kafka_lite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{7}
}

func (x *ProduceResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	StartOffset   int64                  `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_kafka_lite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{8}
}

func (x *FetchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FetchRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *FetchRequest) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

type FetchReplicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	FetchOffset   int64                  `protobuf:"varint,3,opt,name=fetch_offset,json=fetchOffset,proto3" json:"fetch_offset,omitempty"`
	ReplicaId     int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	LeaderEpoch   int64                  `protobuf:"varint,5,opt,name=leader_epoch,json=leaderEpoch,proto3" json:"leader_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchReplicaRequest) Reset() {
	*x = FetchReplicaRequest{}
	mi := &file_kafka_lite_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReplicaRequest) ProtoMessage() {}

func (x *FetchReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReplicaRequest.ProtoReflect.Descriptor instead.
func (*FetchReplicaRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{9}
}

func (x *FetchReplicaRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FetchReplicaRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *FetchReplicaRequest) GetFetchOffset() int64 {
	if x != nil {
		return x.FetchOffset
	}
	return 0
}

func (x *FetchReplicaRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *FetchReplicaRequest) GetLeaderEpoch() int64 {
	if x != nil {
		return x.LeaderEpoch
	}
	return 0
}

type ReplicaRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	HighWatermark int64                  `protobuf:"varint,2,opt,name=high_watermark,json=highWatermark,proto3" json:"high_watermark,omitempty"`
	LeaderEpoch   int64                  `protobuf:"varint,3,opt,name=leader_epoch,json=leaderEpoch,proto3" json:"leader_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaRecord) Reset() {
	*x = ReplicaRecord{}
	mi := &file_kafka_lite_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaRecord) ProtoMessage() {}

func (x *ReplicaRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaRecord.ProtoReflect.Descriptor instead.
func (*ReplicaRecord) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{10}
}

func (x *ReplicaRecord) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ReplicaRecord) GetHighWatermark() int64 {
	if x != nil {
		return x.HighWatermark
	}
	return 0
}

func (x *ReplicaRecord) GetLeaderEpoch() int64 {
	if x != nil {
		return x.LeaderEpoch
	}
	return 0
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_kafka_lite_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{11}
}

func (x *MetadataRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type PartitionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	BrokerAddr    string                 `protobuf:"bytes,2,opt,name=broker_addr,json=brokerAddr,proto3" json:"broker_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionInfo) Reset() {
	*x = PartitionInfo{}
	mi := &file_kafka_lite_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionInfo) ProtoMessage() {}

func (x *PartitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionInfo.ProtoReflect.Descriptor instead.
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{12}
}

func (x *PartitionInfo) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PartitionInfo) GetBrokerAddr() string {
	if x != nil {
		return x.BrokerAddr
	}
	return ""
}

type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*PartitionInfo       `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_kafka_lite_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{13}
}

func (x *MetadataResponse) GetPartitions() []*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type RegisterBrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBrokerRequest) Reset() {
	*x = RegisterBrokerRequest{}
	mi := &file_kafka_lite_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrokerRequest) ProtoMessage() {}

func (x *RegisterBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrokerRequest.ProtoReflect.Descriptor instead.
func (*RegisterBrokerRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterBrokerRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterBrokerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RegisterBrokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBrokerResponse) Reset() {
	*x = RegisterBrokerResponse{}
	mi := &file_kafka_lite_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrokerResponse) ProtoMessage() {}

func (x *RegisterBrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrokerResponse.ProtoReflect.Descriptor instead.
func (*RegisterBrokerResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{15}
}

type JoinGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_kafka_lite_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{16}
}

func (x *JoinGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinGroupRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *JoinGroupRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type JoinGroupResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AssignedPartitions []int32                `protobuf:"varint,1,rep,packed,name=assigned_partitions,json=assignedPartitions,proto3" json:"assigned_partitions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	mi := &file_kafka_lite_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{17}
}

func (x *JoinGroupResponse) GetAssignedPartitions() []int32 {
	if x != nil {
		return x.AssignedPartitions
	}
	return nil
}

type PartitionOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionOffset) Reset() {
	*x = PartitionOffset{}
	mi := &file_kafka_lite_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionOffset) ProtoMessage() {}

func (x *PartitionOffset) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionOffset.ProtoReflect.Descriptor instead.
func (*PartitionOffset) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{18}
}

func (x *PartitionOffset) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PartitionOffset) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CommitOffsetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Offsets       []*PartitionOffset     `protobuf:"bytes,3,rep,name=offsets,proto3" json:"offsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetsRequest) Reset() {
	*x = CommitOffsetsRequest{}
	mi := &file_kafka_lite_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetsRequest) ProtoMessage() {}

func (x *CommitOffsetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetsRequest.ProtoReflect.Descriptor instead.
func (*CommitOffsetsRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{19}
}

func (x *CommitOffsetsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CommitOffsetsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CommitOffsetsRequest) GetOffsets() []*PartitionOffset {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type CommitOffsetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetsResponse) Reset() {
	*x = CommitOffsetsResponse{}
	mi := &file_kafka_lite_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetsResponse) ProtoMessage() {}

func (x *CommitOffsetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetsResponse.ProtoReflect.Descriptor instead.
func (*CommitOffsetsResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{20}
}

type UpdatePartitionLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	BrokerAddr    string                 `protobuf:"bytes,3,opt,name=broker_addr,json=brokerAddr,proto3" json:"broker_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePartitionLeaderRequest) Reset() {
	*x = UpdatePartitionLeaderRequest{}
	mi := &file_kafka_lite_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePartitionLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartitionLeaderRequest) ProtoMessage() {}

func (x *UpdatePartitionLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartitionLeaderRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartitionLeaderRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{21}
}

func (x *UpdatePartitionLeaderRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *UpdatePartitionLeaderRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *UpdatePartitionLeaderRequest) GetBrokerAddr() string {
	if x != nil {
		return x.BrokerAddr
	}
	return ""
}

type UpdatePartitionLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePartitionLeaderResponse) Reset() {
	*x = UpdatePartitionLeaderResponse{}
	mi := &file_kafka_lite_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePartitionLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartitionLeaderResponse) ProtoMessage() {}

func (x *UpdatePartitionLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartitionLeaderResponse.ProtoReflect.Descriptor instead.
func (*UpdatePartitionLeaderResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{22}
}

type AlterIsrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Epoch         int64                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	IsrIds        []int32                `protobuf:"varint,4,rep,packed,name=isr_ids,json=isrIds,proto3" json:"isr_ids,omitempty"` // broker IDs currently in sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterIsrRequest) Reset() {
	*x = AlterIsrRequest{}
	mi := &file_kafka_lite_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterIsrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterIsrRequest) ProtoMessage() {}

func (x *AlterIsrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterIsrRequest.ProtoReflect.Descriptor instead.
func (*AlterIsrRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{23}
}

func (x *AlterIsrRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AlterIsrRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *AlterIsrRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AlterIsrRequest) GetIsrIds() []int32 {
	if x != nil {
		return x.IsrIds
	}
	return nil
}

type AlterIsrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlterIsrResponse) Reset() {
	*x = AlterIsrResponse{}
	mi := &file_kafka_lite_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlterIsrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterIsrResponse) ProtoMessage() {}

func (x *AlterIsrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterIsrResponse.ProtoReflect.Descriptor instead.
func (*AlterIsrResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{24}
}

type InitPartitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions    []int32                `protobuf:"varint,2,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitPartitionsRequest) Reset() {
	*x = InitPartitionsRequest{}
	mi := &file_kafka_lite_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPartitionsRequest) ProtoMessage() {}

func (x *InitPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPartitionsRequest.ProtoReflect.Descriptor instead.
func (*InitPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{25}
}

func (x *InitPartitionsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *InitPartitionsRequest) GetPartitions() []int32 {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type InitPartitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitPartitionsResponse) Reset() {
	*x = InitPartitionsResponse{}
	mi := &file_kafka_lite_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPartitionsResponse) ProtoMessage() {}

func (x *InitPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_lite_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPartitionsResponse.ProtoReflect.Descriptor instead.
func (*InitPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_kafka_lite_proto_rawDescGZIP(), []int{26}
}

var File_kafka_lite_proto protoreflect.FileDescriptor

const file_kafka_lite_proto_rawDesc = "" +
	"\n" +
	"\x10kafka_lite.proto\x12\n" +
	"kafka_lite\"}\n" +
	"\aMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\"D\n" +
	"\x0eTopicPartition\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\"\xe1\x01\n" +
	"\x11AssignRoleRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12+\n" +
	"\x04role\x18\x03 \x01(\x0e2\x17.kafka_lite.ReplicaRoleR\x04role\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x03R\x05epoch\x12\x1b\n" +
	"\tleader_id\x18\x05 \x01(\x05R\bleaderId\x12\x1f\n" +
	"\vleader_addr\x18\x06 \x01(\tR\n" +
	"leaderAddr\x12\x17\n" +
	"\aisr_ids\x18\a \x03(\x05R\x06isrIds\"\x14\n" +
	"\x12AssignRoleResponse\"J\n" +
	"\x12CreateTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x01(\x05R\n" +
	"partitions\"\x15\n" +
	"\x13CreateTopicResponse\"l\n" +
	"\x0eProduceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\")\n" +
	"\x0fProduceResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\"e\n" +
	"\fFetchRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12!\n" +
	"\fstart_offset\x18\x03 \x01(\x03R\vstartOffset\"\xae\x01\n" +
	"\x13FetchReplicaRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12!\n" +
	"\ffetch_offset\x18\x03 \x01(\x03R\vfetchOffset\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x12!\n" +
	"\fleader_epoch\x18\x05 \x01(\x03R\vleaderEpoch\"\x88\x01\n" +
	"\rReplicaRecord\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.kafka_lite.MessageR\amessage\x12%\n" +
	"\x0ehigh_watermark\x18\x02 \x01(\x03R\rhighWatermark\x12!\n" +
	"\fleader_epoch\x18\x03 \x01(\x03R\vleaderEpoch\"'\n" +
	"\x0fMetadataRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"N\n" +
	"\rPartitionInfo\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x1f\n" +
	"\vbroker_addr\x18\x02 \x01(\tR\n" +
	"brokerAddr\"M\n" +
	"\x10MetadataResponse\x129\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x19.kafka_lite.PartitionInfoR\n" +
	"partitions\";\n" +
	"\x15RegisterBrokerRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"\x18\n" +
	"\x16RegisterBrokerResponse\"`\n" +
	"\x10JoinGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"D\n" +
	"\x11JoinGroupResponse\x12/\n" +
	"\x13assigned_partitions\x18\x01 \x03(\x05R\x12assignedPartitions\"G\n" +
	"\x0fPartitionOffset\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"~\n" +
	"\x14CommitOffsetsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x125\n" +
	"\aoffsets\x18\x03 \x03(\v2\x1b.kafka_lite.PartitionOffsetR\aoffsets\"\x17\n" +
	"\x15CommitOffsetsResponse\"s\n" +
	"\x1cUpdatePartitionLeaderRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x1f\n" +
	"\vbroker_addr\x18\x03 \x01(\tR\n" +
	"brokerAddr\"\x1f\n" +
	"\x1dUpdatePartitionLeaderResponse\"t\n" +
	"\x0fAlterIsrRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch\x12\x17\n" +
	"\aisr_ids\x18\x04 \x03(\x05R\x06isrIds\"\x12\n" +
	"\x10AlterIsrResponse\"M\n" +
	"\x15InitPartitionsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x03(\x05R\n" +
	"partitions\"\x18\n" +
	"\x16InitPartitionsResponse*'\n" +
	"\vReplicaRole\x12\n" +
	"\n" +
	"\x06LEADER\x10\x00\x12\f\n" +
	"\bFOLLOWER\x10\x012\xca\x03\n" +
	"\x06Broker\x12N\n" +
	"\vCreateTopic\x12\x1e.kafka_lite.CreateTopicRequest\x1a\x1f.kafka_lite.CreateTopicResponse\x12B\n" +
	"\aProduce\x12\x1a.kafka_lite.ProduceRequest\x1a\x1b.kafka_lite.ProduceResponse\x128\n" +
	"\x05Fetch\x12\x18.kafka_lite.FetchRequest\x1a\x13.kafka_lite.Message0\x01\x12L\n" +
	"\fFetchReplica\x12\x1f.kafka_lite.FetchReplicaRequest\x1a\x19.kafka_lite.ReplicaRecord0\x01\x12W\n" +
	"\x0eInitPartitions\x12!.kafka_lite.InitPartitionsRequest\x1a\".kafka_lite.InitPartitionsResponse\x12K\n" +
	"\n" +
	"AssignRole\x12\x1d.kafka_lite.AssignRoleRequest\x1a\x1e.kafka_lite.AssignRoleResponse2\xd5\x04\n" +
	"\vCoordinator\x12N\n" +
	"\vCreateTopic\x12\x1e.kafka_lite.CreateTopicRequest\x1a\x1f.kafka_lite.CreateTopicResponse\x12H\n" +
	"\vGetMetadata\x12\x1b.kafka_lite.MetadataRequest\x1a\x1c.kafka_lite.MetadataResponse\x12W\n" +
	"\x0eRegisterBroker\x12!.kafka_lite.RegisterBrokerRequest\x1a\".kafka_lite.RegisterBrokerResponse\x12H\n" +
	"\tJoinGroup\x12\x1c.kafka_lite.JoinGroupRequest\x1a\x1d.kafka_lite.JoinGroupResponse\x12T\n" +
	"\rCommitOffsets\x12 .kafka_lite.CommitOffsetsRequest\x1a!.kafka_lite.CommitOffsetsResponse\x12l\n" +
	"\x15UpdatePartitionLeader\x12(.kafka_lite.UpdatePartitionLeaderRequest\x1a).kafka_lite.UpdatePartitionLeaderResponse\x12E\n" +
	"\bAlterIsr\x12\x1b.kafka_lite.AlterIsrRequest\x1a\x1c.kafka_lite.AlterIsrResponseB=Z;github.com/thanhlongnt/kafka-lite/internal/proto/kafka_liteb\x06proto3"

var (
	file_kafka_lite_proto_rawDescOnce sync.Once
	file_kafka_lite_proto_rawDescData []byte
)

func file_kafka_lite_proto_rawDescGZIP() []byte {
	file_kafka_lite_proto_rawDescOnce.Do(func() {
		file_kafka_lite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafka_lite_proto_rawDesc), len(file_kafka_lite_proto_rawDesc)))
	})
	return file_kafka_lite_proto_rawDescData
}

var file_kafka_lite_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kafka_lite_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_kafka_lite_proto_goTypes = []any{
	(ReplicaRole)(0),                      // 0: kafka_lite.ReplicaRole
	(*Message)(nil),                       // 1: kafka_lite.Message
	(*TopicPartition)(nil),                // 2: kafka_lite.TopicPartition
	(*AssignRoleRequest)(nil),             // 3: kafka_lite.AssignRoleRequest
	(*AssignRoleResponse)(nil),            // 4: kafka_lite.AssignRoleResponse
	(*CreateTopicRequest)(nil),            // 5: kafka_lite.CreateTopicRequest
	(*CreateTopicResponse)(nil),           // 6: kafka_lite.CreateTopicResponse
	(*ProduceRequest)(nil),                // 7: kafka_lite.ProduceRequest
	(*ProduceResponse)(nil),               // 8: kafka_lite.ProduceResponse
	(*FetchRequest)(nil),                  // 9: kafka_lite.FetchRequest
	(*FetchReplicaRequest)(nil),           // 10: kafka_lite.FetchReplicaRequest
	(*ReplicaRecord)(nil),                 // 11: kafka_lite.ReplicaRecord
	(*MetadataRequest)(nil),               // 12: kafka_lite.MetadataRequest
	(*PartitionInfo)(nil),                 // 13: kafka_lite.PartitionInfo
	(*MetadataResponse)(nil),              // 14: kafka_lite.MetadataResponse
	(*RegisterBrokerRequest)(nil),         // 15: kafka_lite.RegisterBrokerRequest
	(*RegisterBrokerResponse)(nil),        // 16: kafka_lite.RegisterBrokerResponse
	(*JoinGroupRequest)(nil),              // 17: kafka_lite.JoinGroupRequest
	(*JoinGroupResponse)(nil),             // 18: kafka_lite.JoinGroupResponse
	(*PartitionOffset)(nil),               // 19: kafka_lite.PartitionOffset
	(*CommitOffsetsRequest)(nil),          // 20: kafka_lite.CommitOffsetsRequest
	(*CommitOffsetsResponse)(nil),         // 21: kafka_lite.CommitOffsetsResponse
	(*UpdatePartitionLeaderRequest)(nil),  // 22: kafka_lite.UpdatePartitionLeaderRequest
	(*UpdatePartitionLeaderResponse)(nil), // 23: kafka_lite.UpdatePartitionLeaderResponse
	(*AlterIsrRequest)(nil),               // 24: kafka_lite.AlterIsrRequest
	(*AlterIsrResponse)(nil),              // 25: kafka_lite.AlterIsrResponse
	(*InitPartitionsRequest)(nil),         // 26: kafka_lite.InitPartitionsRequest
	(*InitPartitionsResponse)(nil),        // 27: kafka_lite.InitPartitionsResponse
}
var file_kafka_lite_proto_depIdxs = []int32{
	0,  // 0: kafka_lite.AssignRoleRequest.role:type_name -> kafka_lite.ReplicaRole
	1,  // 1: kafka_lite.ReplicaRecord.message:type_name -> kafka_lite.Message
	13, // 2: kafka_lite.MetadataResponse.partitions:type_name -> kafka_lite.PartitionInfo
	19, // 3: kafka_lite.CommitOffsetsRequest.offsets:type_name -> kafka_lite.PartitionOffset
	5,  // 4: kafka_lite.Broker.CreateTopic:input_type -> kafka_lite.CreateTopicRequest
	7,  // 5: kafka_lite.Broker.Produce:input_type -> kafka_lite.ProduceRequest
	9,  // 6: kafka_lite.Broker.Fetch:input_type -> kafka_lite.FetchRequest
	10, // 7: kafka_lite.Broker.FetchReplica:input_type -> kafka_lite.FetchReplicaRequest
	26, // 8: kafka_lite.Broker.InitPartitions:input_type -> kafka_lite.InitPartitionsRequest
	3,  // 9: kafka_lite.Broker.AssignRole:input_type -> kafka_lite.AssignRoleRequest
	5,  // 10: kafka_lite.Coordinator.CreateTopic:input_type -> kafka_lite.CreateTopicRequest
	12, // 11: kafka_lite.Coordinator.GetMetadata:input_type -> kafka_lite.MetadataRequest
	15, // 12: kafka_lite.Coordinator.RegisterBroker:input_type -> kafka_lite.RegisterBrokerRequest
	17, // 13: kafka_lite.Coordinator.JoinGroup:input_type -> kafka_lite.JoinGroupRequest
	20, // 14: kafka_lite.Coordinator.CommitOffsets:input_type -> kafka_lite.CommitOffsetsRequest
	22, // 15: kafka_lite.Coordinator.UpdatePartitionLeader:input_type -> kafka_lite.UpdatePartitionLeaderRequest
	24, // 16: kafka_lite.Coordinator.AlterIsr:input_type -> kafka_lite.AlterIsrRequest
	6,  // 17: kafka_lite.Broker.CreateTopic:output_type -> kafka_lite.CreateTopicResponse
	8,  // 18: kafka_lite.Broker.Produce:output_type -> kafka_lite.ProduceResponse
	1,  // 19: kafka_lite.Broker.Fetch:output_type -> kafka_lite.Message
	11, // 20: kafka_lite.Broker.FetchReplica:output_type -> kafka_lite.ReplicaRecord
	27, // 21: kafka_lite.Broker.InitPartitions:output_type -> kafka_lite.InitPartitionsResponse
	4,  // 22: kafka_lite.Broker.AssignRole:output_type -> kafka_lite.AssignRoleResponse
	6,  // 23: kafka_lite.Coordinator.CreateTopic:output_type -> kafka_lite.CreateTopicResponse
	14, // 24: kafka_lite.Coordinator.GetMetadata:output_type -> kafka_lite.MetadataResponse
	16, // 25: kafka_lite.Coordinator.RegisterBroker:output_type -> kafka_lite.RegisterBrokerResponse
	18, // 26: kafka_lite.Coordinator.JoinGroup:output_type -> kafka_lite.JoinGroupResponse
	21, // 27: kafka_lite.Coordinator.CommitOffsets:output_type -> kafka_lite.CommitOffsetsResponse
	23, // 28: kafka_lite.Coordinator.UpdatePartitionLeader:output_type -> kafka_lite.UpdatePartitionLeaderResponse
	25, // 29: kafka_lite.Coordinator.AlterIsr:output_type -> kafka_lite.AlterIsrResponse
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_kafka_lite_proto_init() }
func file_kafka_lite_proto_init() {
	if File_kafka_lite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafka_lite_proto_rawDesc), len(file_kafka_lite_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kafka_lite_proto_goTypes,
		DependencyIndexes: file_kafka_lite_proto_depIdxs,
		EnumInfos:         file_kafka_lite_proto_enumTypes,
		MessageInfos:      file_kafka_lite_proto_msgTypes,
	}.Build()
	File_kafka_lite_proto = out.File
	file_kafka_lite_proto_goTypes = nil
	file_kafka_lite_proto_depIdxs = nil
}
